#:schema node_modules/wrangler/config-schema.json
name = "chat-with-pdf"
compatibility_date = "2024-07-29"
pages_build_output_dir = "./build/client"

[[r2_buckets]]
binding = "pdfs-bucket"
bucket_name = "pdfs"
